export const eventsMockData = [
    {
        id: 1,
        title: 'Montreal International Jazz Festival',
        category: 'Featured',
        date: '2026-06-25T19:00:00',
        location: 'Place des Arts, Montreal',
        organization: 'Evenko',
        description: 'Experience the world\'s largest jazz festival, featuring legendary artists and rising stars in the heart of downtown Montreal.',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2070&auto=format&fit=crop',
        price: 55,
    },
    {
        id: 2,
        title: 'Indie Music Festival',
        category: 'Music',
        date: '2025-11-12T18:00:00',
        location: 'Parc Jean-Drapeau, Montreal',
        organization: 'Osheaga',
        description: 'A two-day festival showcasing the best up-and-coming indie bands from across the country.',
        imageUrl: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?q=80&w=2070&auto=format&fit=crop',
        price: 75,
    },
    {
        id: 3,
        title: 'Startup Pitch Night',
        category: 'Business',
        date: '2025-11-05T19:00:00',
        location: 'Innovation Hub, Montreal',
        organization: 'Startup Montreal',
        description: 'Watch the city\'s brightest entrepreneurs pitch their ideas to a panel of venture capitalists.',
        imageUrl: 'https://images.unsplash.com/photo-1560439514-4e9645039924?q=80&w=2070&auto=format&fit=crop',
        price: 15,
    },
    {
        id: 4,
        title: 'Advanced React Workshop',
        category: 'Technology',
        date: '2025-11-18T10:00:00',
        location: 'Online',
        organization: 'Concordia Continuing Education',
        description: 'Deep dive into advanced React patterns, hooks, and performance optimization techniques.',
        imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
        price: 250,
    },
    {
        id: 5,
        title: 'City Marathon 2025',
        category: 'Sports',
        date: '2025-10-19T07:00:00',
        location: 'Mount Royal Park, Montreal',
        organization: 'Run Montreal',
        description: 'Join thousands of runners in the annual city marathon. All skill levels welcome.',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=2070&auto=format&fit=crop',
        price: 40,
    },
    {
        id: 6,
        title: 'Artisan Market Fair',
        category: 'Community',
        date: '2025-10-26T11:00:00',
        location: 'Old Port, Montreal',
        organization: 'City of Montreal',
        description: 'Discover unique handmade crafts, local food, and live music at our weekend market.',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop',
        price: 'Free',
    },
    {
        id: 7,
        title: 'Annual Tech Summit 2025',
        category: 'Featured',
        date: '2025-10-25T09:00:00',
        location: 'Convention Center, Montreal',
        organization: 'Tech Summit Inc.',
        description: 'Join industry leaders to discuss the future of technology, from AI to quantum computing.',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop',
        price: 499,
    },
    {
        id: 8,
        title: 'Film Noir Retrospective',
        category: 'Arts & Culture',
        date: '2025-11-20T19:00:00',
        location: 'Cinéma du Parc, Montreal',
        organization: 'Cinéma du Parc',
        description: 'A month-long retrospective celebrating the dark and stylish world of classic film noir.',
        imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963e?q=80&w=2070&auto=format&fit=crop',
        price: 12,
    },
    {
        id: 9,
        title: 'Oktoberfest Montreal',
        category: 'Food & Drink',
        date: '2025-10-11T14:00:00',
        location: 'Lachine Canal, Montreal',
        organization: 'Les Amis du Canal',
        description: 'Enjoy a taste of Bavaria with craft beer, traditional food, and live oompah bands.',
        imageUrl: 'https://images.unsplash.com/photo-1598801269323-315159d84f83?q=80&w=2070&auto=format&fit=crop',
        price: 20,
    },
    {
        id: 10,
        title: 'Oktoberfest - Day 2',
        category: 'Food & Drink',
        date: '2025-10-12T14:00:00',
        location: 'Lachine Canal, Montreal',
        organization: 'Les Amis du Canal',
        description: 'Enjoy a taste of Bavaria with craft beer, traditional food, and live oompah bands.',
        imageUrl: 'https://images.unsplash.com/photo-1598801269323-315159d84f83?q=80&w=2070&auto=format&fit=crop',
        price: 20,
    },
    {
        id: 19,
        title: 'Christmas Morning Brunch',
        category: 'Food & Drink',
        date: '2025-12-25T11:00:00',
        location: 'Ritz-Carlton Montreal',
        organization: 'Ritz-Carlton',
        description: 'A festive brunch to celebrate Christmas day with family and friends.',
        imageUrl: 'https://images.unsplash.com/photo-1606816223793-2009a0a0d165',
        price: 125,
    },
    {
        id: 20,
        title: 'Skating at Beaver Lake',
        category: 'Sports',
        date: '2025-12-25T14:00:00',
        location: 'Mount Royal Park, Montreal',
        organization: 'City of Montreal',
        description: 'Enjoy a beautiful Christmas afternoon skating on the picturesque Beaver Lake.',
        imageUrl: 'https://images.unsplash.com/photo-1546553336-1a52c39c8a24',
        price: 'Free',
    },
    {
        id: 21,
        title: 'Christmas Carol Concert',
        category: 'Music',
        date: '2025-12-25T16:00:00',
        location: 'Notre-Dame Basilica',
        organization: 'Montreal Symphony Orchestra',
        description: 'A magical concert of classic Christmas carols in a stunning setting.',
        imageUrl: 'https://images.unsplash.com/photo-1513297886289-86435f79a8a7',
        price: 60,
    },
    {
        id: 22,
        title: 'Holiday Movie Marathon',
        category: 'Arts & Culture',
        date: '2025-12-25T18:00:00',
        location: 'Cinéma du Parc, Montreal',
        organization: 'Cinéma du Parc',
        description: 'Watch your favorite holiday classics back-to-back on the big screen.',
        imageUrl: 'https://images.unsplash.com/photo-1574979142799-73b3c5a6b572',
        price: 20,
    },
    {
        id: 23,
        title: 'Festive Lights Walking Tour',
        category: 'Community',
        date: '2025-12-25T20:00:00',
        location: 'Old Port, Montreal',
        organization: 'MTL Detours',
        description: 'A guided walking tour to see the best Christmas lights and decorations in Old Montreal.',
        imageUrl: 'https://images.unsplash.com/photo-1512133211758-613abf44c1c9',
        price: 15,
    }
];
