name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install root dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: npm ci --prefix frontend

    - name: Run ESLint on frontend
      run: npm run lint --prefix frontend

    - name: Build frontend
      run: npm run build --prefix frontend

  backend-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install root dependencies
      run: npm ci

    - name: Run backend API tests
      run: npm test
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret-key-for-ci-testing

