name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install root dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: npm ci --prefix frontend

    - name: Run ESLint on frontend
      run: npm run lint --prefix frontend

    - name: Build frontend
      run: npm run build --prefix frontend

    - name: Check backend syntax
      run: |
        echo "Checking backend JavaScript syntax..."
        find backend -name "*.js" -type f ! -path "*/node_modules/*" ! -path "*/tests/*" | while read file; do
          echo "Checking: $file"
          node --check "$file" || exit 1
        done
      continue-on-error: false

